services:
  # The name of the service (can be anything, like 'database' or 'backend-db')
  postgres_db:
    # Use the official PostgreSQL image (you can specify a version like 'postgres:16-alpine')
    image: postgres:latest
    
    # Map the container's default port (5432) to the host machine's port (5432)
    ports:
      - "5432:5432"
      
    # Set environment variables for configuration. These are crucial for initial setup.
    environment:
      # The initial database to be created
      POSTGRES_DB: proyecto_bdd
      # The initial user to be created
      POSTGRES_USER: postgres
      # The password for the user (CHANGE THIS IN PRODUCTION!)
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
      
    # Use a named volume AND a bind mount
    volumes:
      # 1. Named Volume (Persistence for Database Data)
      - postgres_data:/var/lib/postgresql

      - ./db_scripts:/docker-entrypoint-initdb.d

      - ./scripts:/tmp/scripts
      
    # Restart the container if it exits, unless manually stopped
    restart: always

# Define the named volume for persistence
volumes:
  postgres_data:
    # Driver can be omitted, defaults to 'local'
